### ISSUE TITLE
Planning 1st PWA roadshow 101 for VB

### ISSUE THREAD

**Issue by ragingwind** [pwa-workshop/roadshow#1]
## Information

- Title: Progressive Web App Roadshow 101 for Very Beginners (촙촙)
- Location: [CNN the Biz](https://goo.gl/pmvt2) 강남역, 서울
- Datetime: 2016-12-20, 화요일(TUE)

## Programs

- [x] 빠르게 접근가능한 모바일 페이지 만들기 (by AMP), < 20m, @techhtml
- [x] 오프라인 웹앱 만들기 (by Service Worker), < 20m, @cwdoh
- [x] 설치형 웹앱 만들기 (by Web Manifest), < 20m, @ragingwind

## Codelab #1 > 90min
- [x] 어플리케이션 꾸미기
- [x] 가이드 for AMP
- [x] 가이드 for Service Worker
- [x] Web Manifest

## TODOs

- [x] CNN the Biz 정소 섭외 확정
- [x] [Swags](https://drive.google.com/drive/u/0/folders/0B55wxScz_BJtUkRNNUNsX0luN0U) 제작 => 2차 코드랩때 지원

**Comment by ragingwind** [comment]
@techhtml 가시기전에 가능하다면 세션 제목(가칭이라도)이랑 시간만 알려주심

**Comment by techhtml** [comment]
**@techhtml:** 빠르게 접근가능한 모바일 페이지 만들기 (by AMP)

**Comment by techhtml** [comment]
time은 20분정도면 될 거 같아요. 세미나에서는 AMP가 대충 어떻게 굴러가는 지만 보여주고 끝낼거라.

**Comment by cwdoh** [comment]
서비스워커는 이전 히스토리는 날리고, Offline cache만 다루면 시간이 맞을 것 같기는 하네요.

**Comment by ragingwind** [comment]
문서를 업데이트 했습니다. uncheck 된 부분은 완료되면 작성하면 될 것 같습니다. 의논해봐야할 부분이

- 1차 코드랩 튜토리얼 작성
- Swags

Swags 는 업데이트 내용있으면 좀 알려주시구요. 개인적으로는 옵션입니다. 1차 코드랩은, 제가 저번에 이야기 드린 AMP -> Offline Cache -> Installable 앱으로 되는 `진짜` Single Page Web App 이 적당하다고 생각합니다. 다른 의견 부탁드려요

**Comment by cwdoh** [comment]
일단 흐름은 맞는 것 같습니다. 그리고 swag은 지금 신경쓰기보다는 코드랩 때 줘도 될 것 같기도 합니다. :)

2016년 11월 21일 (월) 오후 8:41, Jimmy Moon <notifications@github.com>님이 작성:

**Comment by ragingwind** [comment]
그럼 1차 코드랩 시나리오/구성은 어떻게 할까요?

**Comment by cwdoh** [comment]
이런 순서는 어떨까요

1. AMP Name 카드 마크업 작성
2. 스타일링
3. Validating AMP
4. amp-install-serviceworker 를 사용한 offline
5. installable webapp manifest 설정
6. 배포(?)

**Comment by ragingwind** [comment]
namp-card?

**Comment by ragingwind** [comment]
그냥 하나 만들었습니다. 초기 작업하고 알려드릴께요 그 다음에 각 브랜치로 작업하면 될 것 같네요

- https://github.com/pwa-workshop/namp-card

**Comment by ragingwind** [comment]
@cwdoh friendlyping, 지금 쯤 어나운스해야하지 않을까요? 장소와 시간?

**Comment by cwdoh** [comment]
* Google Event: https://developers.google.com/events/6323277414531072/
* 모집 URL: http://onoffmix.com/event/85133

**Comment by ragingwind** [comment]
베리 비기너라서 npm, github 같은 경우도 명시해야할 것 같네요

**Comment by ragingwind** [comment]
https://github.com/pwa-workshop/namp-card 초기 프로젝트 셋팅했습니다. forking 하셔서 작업하시면 될 것 같네요. 저는 manifest 랑 github page 에 deploy 하는거 알아볼께요

**Comment by cwdoh** [comment]
http://onoffmix.com/event/85133 으로 공지하면 됩니다.

**Comment by cwdoh** [comment]
npm github 등도 명시했어요.
[http://onoffmix.com/event/85133](http://onoffmix.com/event/85133)로 공지 시작합니다.

**Comment by ragingwind** [comment]
@cwdoh 온오프믹스는 에디터 권환주고 이런 기능 없죠?

**Comment by cwdoh** [comment]
찾아보는데 그런 기능이 안보이네요. 불편ㅡㅡ

2016년 12월 5일 (월) 오후 1:30, Jimmy Moon <notifications@github.com>님이 작성:

**Comment by ragingwind** [comment]
- 코드랩 앱은 일단 deploy 해봤습니다 잘 되네요 https://pwa-workshop.github.io/namp-card/

@techhtml @cwdoh 코드랩 튜토리얼 문서 작성하셔야 하는데 앱 완성이 어디까지인지 명확하지 않아서 https://github.com/pwa-workshop/namp-card/issues/7 에 일단 썹업 해야 할 것 같으니, 생각나는대로 적어주세요

**Comment by ragingwind** [comment]
다음에는 https://github.com/googlecodelabs/your-first-pwapp 이 정도 레벨은 안되려나요

**Comment by cwdoh** [comment]
이정도 레벨은 무리가 안될 것 같은데요. App Shell만 추가로 학습하는 수준일 듯 :)

**Comment by ragingwind** [comment]
다들 휴가 잘 보내시고 계신데.. 그래도 날짜가 얼마 안남아 핑합니다. 마무리 안된 것이 좀 있습니다.

- 코드랩 자료
- PPT, 이건 걱정이 안됩니다

**Comment by ragingwind** [comment]
저는 PT 는 작성해서 올렸습니다 https://github.com/pwa-workshop/roadshow/blob/master/turn-into-an-installable-webapp.md @techhtml @cwdoh 상황이 어떠세요?

**Comment by ragingwind** [comment]
가이드 추가했습니다. https://github.com/pwa-workshop/namp-card/commit/8e3422f74575d763f86962b32b09d838e331816c

**Comment by cwdoh** [comment]
저는 리드미 작성 중이고요. 슬라이드는 이전 서비스워커 내용에서 발췌해서 사용할 예정입니다.

2016년 12월 19일 (월) 오전 11:13, Jimmy Moon <notifications@github.com>님이 작성:

**Comment by techhtml** [comment]
오늘 슬라이드 작성해둘게요-

**Comment by techhtml** [comment]
코드랩에 있는 AMP 페이지를 좀 변경했고 리드미쪽도 업데이트 해두었습니다.

**Comment by cwdoh** [comment]
@ragingwind 현재 대기자 17명 있는데 그냥 받을까 하는 생각도 드네요.

**Comment by ragingwind** [comment]
PT 는 가능하시면 여기에 commit 해주세요.

**Comment by ragingwind** [comment]
모두 수고하셨습니다. 짝짝 그레잇잡!
