### ISSUE TITLE
Planning 1st revival PWA roadshow 

### ISSUE THREAD

**Issue by ragingwind** [pwa-workshop/roadshow#3]
## Information

- Title: Progressive Web App Roadshow 101 for 캠퍼스 뉴비피플
- Location: 토즈 (강남 토즈타워점)
- Datetime: 2017-02-26(일요일) 14:00 ~ 18:00

## TODOs

- [x] 장소/시간 선정
- [x] 코드랩 업데이트, 스텝 바이 스텝 형태로 혼자서도 가능하게 assigned by @ragingwind
- [x] 공지: 서울 캠퍼스에서 맡아 주는 것으로

**Comment by ragingwind** [comment]
@cwdoh @techhtml 장소/시간 확정하고 공지해야할 것 같습니다.

**Comment by techhtml** [comment]
장소를 지금 대여할 수 있는 공간이 있을까요?
서울이 아닌 지역도 괜찮을 거 같은데, 대여할만한 공간이 있을 지가 고민이네요.

**Comment by cwdoh** [comment]
학교 같으면 딱 좋을 것 같기는 한데, 만만하지는 않을 것 같기도...;;

**Comment by ragingwind** [comment]
한번 구글에 문의를 해볼까요? 저도 지방 학교가 재미있을 것 같습니다

**Comment by ragingwind** [comment]
@techhtml 장소/일정 업데이트 부탁드려요

**Comment by techhtml** [comment]
장소는 강남역 토즈 (토즈타워점)
인원은 50명까지 수용 가능합니다.

**Comment by ragingwind** [comment]
코드랩 문서만 정리하면 될 것 같은데 제가 할께요. 나중에 리뷰 해주세요. 일단 설명은 빼고 스텝바이 스텝으로 하려고 합니다
